---
title: "Reporte indicadores - Financial Sustainability"
author:
- "Researcher: Dr. Gabriel Purón Cid"
- "Research assistant: Erick Gabriel Fajardo Martínez"
date: '`r format(Sys.time(), "%d %B %Y")`'
fontsize: 12pt
output: html
fig-cap-location: top
fig-align: center
lang: es
---

```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(scipen = 99999)

# Librerias
library(tidyverse)
library(kableExtra)

# Lectura 
indicadores_fs <- read_csv(here::here("./data/3_final/indicadores_fs.csv"))
```

# Cálculo de los indicadores

## Cash Solvency

- `cs_revenue_perCapita`

$$
\begin{aligned}
\text{Revenue per capita} = \frac{\text{Total revenues}}{\text{Population}}
\end{aligned}
$$

- `cs_total_general_fund`

$$
\begin{aligned}
\text{Total general fund revenues from own sources} &= \frac{\text{Unassigned fund}}{\text{Total general fund sources}} = \frac{\text{impuestos + contribuciones de mejoras + derechos + productos + aprovechamientos}}{\text{impuestos + contribuciones de mejoras + derechos + productos + aprovechamientos + participaciones federales + aportaciones federales y estatales}} 
\end{aligned}
$$

- `cs_intergov_revs_total_revs`

$$
\begin{aligned}
\frac{\text{Intergovernmental revenues}}{\text{Total revenues}} = \frac{\text{participaciones federales + aportaciones federales y estatales}}{\text{Total revenues}}
\end{aligned}
$$

- `cs_propety_tax_total_revs`

$$
\frac{\text{Property tax}}{\text{Total revenues}} = \frac{\text{impuestos sobre el patrimonio}}{\text{Ingresos totales}}
$$

## Budget Solvency

- `bs_operating_exp`

$$
\frac{\text{Operating expenditures}}{\text{Total expenditures}} = \frac{\text{servicios personales + materiales y suministros + servicios generales}}{\text{Gastos totales}}
$$

- `bs_operating_balance`

$$
\text{Operating balance} = \frac{\text{Total revenues}}{\text{Total expenditures}} 
$$

## Long-run Solvency

- `lrs_direct_long_term_debt_pobtot`

$$
\frac{\text{Direct long term debt}}{\text{Population}} = \frac{\text{Financiamiento}}{\text{Población}}
$$

- `lrs_debt_service_total_rev`

$$
\frac{\text{Debt service}}{\text{Total revenues}} = \frac{\text{Deuda pública}}{\text{Ingresos totales}}
$$

|
|
|
|

```{r conjunto_de_datos}
#| label: tbl-head
#| tbl-cap: "Conjunto de datos de los indicadores"
#| #| layout: "[[1], [-1], [1]]"

head(indicadores_fs) %>%
  kable(col.names = c("Municipio INEGI", "Año", names(indicadores_fs)[3:11])) %>%
  kable_styling(position = "center", latex_options = c("HOLD_position", "scale_down"))
```

|
|
|
|

```{r EDA}
#| label: fig-na
#| fig-cap: Cantidad de valores daltantes por indicador y año
#| fig-cap-location: top
#| layout: "[[1], [-1], [1]]"

# Cantidad de NAs por indicador
indicadores_fs %>%
  select(-mun_inegi) %>%
  group_by(anio) %>%
  summarise(across(everything(), ~ sum(is.na(.x)))) %>%
  pivot_longer(names_to = "indicador", values_to = "NA_count", cols = -c(anio)) %>%
  mutate(fs_class = str_extract(indicador, "^[a-z]+")) %>%
  ggplot(aes(NA_count, indicador, col = fs_class)) +
  geom_col(width = 0.1, show.legend = FALSE) +
  geom_point() + 
  scale_color_discrete(name = "Clase indicador") +
  facet_wrap(~anio) +
  labs(
       x = "Valores faltantes") +
  theme_bw()
```

|
|
|
|

```{r descriptive}
#| label: tbl-desc
#| tbl-cap: Estadística descriptiva de los indicadores
#| layout: "[[1], [-1], [1]]"
indicadores_fs %>%
  select(-mun_inegi) %>%
  pivot_longer(names_to = "indicador", values_to = "valor", cols = -anio) %>%
  group_by(anio, indicador) %>%
  summarise(min = min(valor, na.rm = TRUE),  
            media = mean(valor, na.rm = TRUE),
            max = max(valor, na.rm = TRUE),
            sd = sd(valor, na.rm = TRUE)) %>%
  kable(col.names = c("Año", "Indicador", "Min", "Media", "Max", "Desviación Estándar")) %>%
  kable_styling(position = "center", latex_options = c("HOLD_position", "scale_down"))
```
